include .env
export
build:
	go build -o bin/hadiaParfums  cmd/main.go

run: build
	./bin/hadiaParfums

run-bot:
	go run cmd/bot/main.go

test:
	go test -v ./...

createdb:
	docker exec -it postgres19 createdb --username=$(DB_USER) --owner=$(DB_USER) $(DB_NAME)

dropdb:
	docker exec -it postgres19 dropdb $(DB_NAME)

postgres:
	docker run --name postgres19 -p $(DB_PORT):5432 -e POSTGRES_USER=$(DB_USER) -e POSTGRES_PASSWORD=$(DB_PASSWORD) -d postgres:19beta1-alpine

migrateup:
	migrate -path migration -database "$(DB_SOURCE)" -verbose up

migratedown:
	migrate -path migration -database "$(DB_SOURCE)" -verbose down

sqlc:
	sqlc generate

.PHONY: createdb, dropdb, migrateup, migratedown, sqlc
