// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int32
	UserID      pgtype.Int4
	ProductID   pgtype.Int4
	Quantity    int32
	Status      pgtype.Text
	Total       pgtype.Numeric
	PromoCodeID pgtype.Int4
	CreatedAt   pgtype.Timestamp
}

type Product struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Category    string
	CreatedAt   pgtype.Timestamp
}

type ProductVariant struct {
	ID        int32
	ProductID pgtype.Int4
	VolumeMl  int32
	Price     pgtype.Numeric
	Stock     pgtype.Int4
	Sku       pgtype.Text
}

type PromoCode struct {
	ID              int32
	Code            string
	DiscountPercent int32
	ValidUntil      pgtype.Timestamp
	UsageLimit      pgtype.Int4
	UsedCount       pgtype.Int4
	IsActive        pgtype.Bool
	CreatedAt       pgtype.Timestamp
}

type User struct {
	ID        int32
	ChatID    int64
	Name      string
	Lang      pgtype.Text
	IsAdmin   pgtype.Bool
	CreatedAt pgtype.Timestamp
}
