// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id,
  product_id,
  quantity,
  total
) VALUES (
  $1, $2, $3, $4
)RETURNING id, user_id, product_id, quantity, status, total, promo_code_id, created_at
`

type CreateOrderParams struct {
	UserID    pgtype.Int4
	ProductID pgtype.Int4
	Quantity  int32
	Total     pgtype.Numeric
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.ProductID,
		arg.Quantity,
		arg.Total,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.Total,
		&i.PromoCodeID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrderByID = `-- name: DeleteOrderByID :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrderByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrderByID, id)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, product_id, quantity, status, total, promo_code_id, created_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.Total,
		&i.PromoCodeID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByUser = `-- name: GetOrderByUser :one
SELECT id, user_id, product_id, quantity, status, total, promo_code_id, created_at FROM orders
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetOrderByUser(ctx context.Context, userID pgtype.Int4) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByUser, userID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.Total,
		&i.PromoCodeID,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderByID = `-- name: ListOrderByID :many
SELECT id, user_id, product_id, quantity, status, total, promo_code_id, created_at FROM orders
ORDER BY user_id
LIMIT $1
OFFSET $2
`

type ListOrderByIDParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrderByID(ctx context.Context, arg ListOrderByIDParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrderByID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.Status,
			&i.Total,
			&i.PromoCodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderByTime = `-- name: ListOrderByTime :many
SELECT id, user_id, product_id, quantity, status, total, promo_code_id, created_at FROM orders
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListOrderByTimeParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrderByTime(ctx context.Context, arg ListOrderByTimeParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrderByTime, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.Status,
			&i.Total,
			&i.PromoCodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
