// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name,
  price,
  stock,
  description
) VALUES (
  $1, $2, $3, $4
)RETURNING id, name, price, stock, description, created_at
`

type CreateProductParams struct {
	Name        string
	Price       pgtype.Numeric
	Stock       pgtype.Int4
	Description pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price, stock, description, created_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, name, price, stock, description, created_at FROM products
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listProductByID = `-- name: ListProductByID :many
SELECT id, name, price, stock, description, created_at FROM products
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListProductByIDParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductByID(ctx context.Context, arg ListProductByIDParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductByID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductByName = `-- name: ListProductByName :many
SELECT id, name, price, stock, description, created_at FROM products
ORDER BY name
LIMIT $1
OFFSET $2
`

type ListProductByNameParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductByName(ctx context.Context, arg ListProductByNameParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductByName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductPrice = `-- name: UpdateProductPrice :one
UPDATE products
SET price = $2
WHERE id = $1
RETURNING id, name, price, stock, description, created_at
`

type UpdateProductPriceParams struct {
	ID    int32
	Price pgtype.Numeric
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductPrice, arg.ID, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET stock = $2
WHERE id = $1
RETURNING id, name, price, stock, description, created_at
`

type UpdateProductStockParams struct {
	ID    int32
	Stock pgtype.Int4
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
