// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_variants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProdVariants = `-- name: CreateProdVariants :one
INSERT INTO product_variants (
  product_id,
  volume_ml,
  price,
  stock
) VALUES (
  $1, $2, $3, $4 
)RETURNING id, product_id, volume_ml, price, stock, sku
`

type CreateProdVariantsParams struct {
	ProductID pgtype.Int4
	VolumeMl  int32
	Price     pgtype.Numeric
	Stock     pgtype.Int4
}

func (q *Queries) CreateProdVariants(ctx context.Context, arg CreateProdVariantsParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProdVariants,
		arg.ProductID,
		arg.VolumeMl,
		arg.Price,
		arg.Stock,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VolumeMl,
		&i.Price,
		&i.Stock,
		&i.Sku,
	)
	return i, err
}

const decreaseProdVariantStock = `-- name: DecreaseProdVariantStock :one
UPDATE product_variants 
SET stock = stock - $2
WHERE id = $1 AND stock >= $2
RETURNING id, product_id, volume_ml, price, stock, sku
`

type DecreaseProdVariantStockParams struct {
	ID    int32
	Stock pgtype.Int4
}

func (q *Queries) DecreaseProdVariantStock(ctx context.Context, arg DecreaseProdVariantStockParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, decreaseProdVariantStock, arg.ID, arg.Stock)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VolumeMl,
		&i.Price,
		&i.Stock,
		&i.Sku,
	)
	return i, err
}

const deleteProdVariant = `-- name: DeleteProdVariant :exec
DELETE FROM product_variants
WHERE id = $1
`

func (q *Queries) DeleteProdVariant(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProdVariant, id)
	return err
}

const getProdVariantByProductID = `-- name: GetProdVariantByProductID :many
SELECT id, product_id, volume_ml, price, stock, sku FROM product_variants 
WHERE product_id = $1 LIMIT 1
`

func (q *Queries) GetProdVariantByProductID(ctx context.Context, productID pgtype.Int4) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, getProdVariantByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VolumeMl,
			&i.Price,
			&i.Stock,
			&i.Sku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProdVariantID = `-- name: GetProdVariantID :one
SELECT id, product_id, volume_ml, price, stock, sku FROM product_variants 
WHERE id = $1
`

func (q *Queries) GetProdVariantID(ctx context.Context, id int32) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getProdVariantID, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VolumeMl,
		&i.Price,
		&i.Stock,
		&i.Sku,
	)
	return i, err
}

const listProdVariant = `-- name: ListProdVariant :many
SELECT id, product_id, volume_ml, price, stock, sku FROM product_variants
ORDER BY product_id
LIMIT $1
OFFSET $2
`

type ListProdVariantParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProdVariant(ctx context.Context, arg ListProdVariantParams) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listProdVariant, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VolumeMl,
			&i.Price,
			&i.Stock,
			&i.Sku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProdVariantPrice = `-- name: UpdateProdVariantPrice :one
UPDATE product_variants
SET price = $2
WHERE id = $1
RETURNING id, product_id, volume_ml, price, stock, sku
`

type UpdateProdVariantPriceParams struct {
	ID    int32
	Price pgtype.Numeric
}

func (q *Queries) UpdateProdVariantPrice(ctx context.Context, arg UpdateProdVariantPriceParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateProdVariantPrice, arg.ID, arg.Price)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VolumeMl,
		&i.Price,
		&i.Stock,
		&i.Sku,
	)
	return i, err
}

const updateProdVariantStock = `-- name: UpdateProdVariantStock :one
UPDATE product_variants
SET stock = $2
WHERE id = $1
RETURNING id, product_id, volume_ml, price, stock, sku
`

type UpdateProdVariantStockParams struct {
	ID    int32
	Stock pgtype.Int4
}

func (q *Queries) UpdateProdVariantStock(ctx context.Context, arg UpdateProdVariantStockParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateProdVariantStock, arg.ID, arg.Stock)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VolumeMl,
		&i.Price,
		&i.Stock,
		&i.Sku,
	)
	return i, err
}

const updateProdVariantVolume = `-- name: UpdateProdVariantVolume :one
UPDATE product_variants
SET volume_ml = $2
WHERE id = $1
RETURNING id, product_id, volume_ml, price, stock, sku
`

type UpdateProdVariantVolumeParams struct {
	ID       int32
	VolumeMl int32
}

func (q *Queries) UpdateProdVariantVolume(ctx context.Context, arg UpdateProdVariantVolumeParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateProdVariantVolume, arg.ID, arg.VolumeMl)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VolumeMl,
		&i.Price,
		&i.Stock,
		&i.Sku,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE product_variants
SET 
    volume_ml = COALESCE($2, volume_ml),
    price = COALESCE($3, price),
    stock = COALESCE($4, stock)
WHERE id = $1
RETURNING id, product_id, volume_ml, price, stock, sku
`

type UpdateVariantParams struct {
	ID       int32
	VolumeMl int32
	Price    pgtype.Numeric
	Stock    pgtype.Int4
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.ID,
		arg.VolumeMl,
		arg.Price,
		arg.Stock,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VolumeMl,
		&i.Price,
		&i.Stock,
		&i.Sku,
	)
	return i, err
}
