// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name,
  category,
  description
) VALUES (
  $1, $2, $3 
)RETURNING id, name, description, category, created_at
`

type CreateProductParams struct {
	Name        string
	Category    string
	Description pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Category, arg.Description)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductByID = `-- name: DeleteProductByID :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProductByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProductByID, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, category, created_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, name, description, category, created_at FROM products
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const listProductByID = `-- name: ListProductByID :many
SELECT id, name, description, category, created_at FROM products
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListProductByIDParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductByID(ctx context.Context, arg ListProductByIDParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductByID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductByName = `-- name: ListProductByName :many
SELECT id, name, description, category, created_at FROM products
WHERE name ILIKE $1
ORDER BY name
LIMIT $2
OFFSET $3
`

type ListProductByNameParams struct {
	Name   string
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductByName(ctx context.Context, arg ListProductByNameParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductByName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductCategory = `-- name: UpdateProductCategory :one
UPDATE products
SET category = $2
WHERE id = $1
RETURNING id, name, description, category, created_at
`

type UpdateProductCategoryParams struct {
	ID       int32
	Category string
}

func (q *Queries) UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductCategory, arg.ID, arg.Category)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const updateProductDiscription = `-- name: UpdateProductDiscription :one
UPDATE products
SET description = $2
WHERE id = $1
RETURNING id, name, description, category, created_at
`

type UpdateProductDiscriptionParams struct {
	ID          int32
	Description pgtype.Text
}

func (q *Queries) UpdateProductDiscription(ctx context.Context, arg UpdateProductDiscriptionParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductDiscription, arg.ID, arg.Description)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}
