// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  chat_id,
  lang,
  name
  
) VALUES (
  $1, $2 , $3
)RETURNING id, chat_id, name, lang, is_admin, created_at
`

type CreateUserParams struct {
	ChatID int64
	Lang   pgtype.Text
	Name   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ChatID, arg.Lang, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Name,
		&i.Lang,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE chat_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, chatID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, chat_id, name, lang, is_admin, created_at FROM users
WHERE chat_id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, chatID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, chatID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Name,
		&i.Lang,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, chat_id, name, lang, is_admin, created_at FROM users
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Name,
		&i.Lang,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const listUser = `-- name: ListUser :many
SELECT id, chat_id, name, lang, is_admin, created_at FROM users
ORDER BY chat_id
LIMIT $1
OFFSET $2
`

type ListUserParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUser(ctx context.Context, arg ListUserParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Name,
			&i.Lang,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET lang = $2
WHERE chat_id = $1
RETURNING id, chat_id, name, lang, is_admin, created_at
`

type UpdateUserParams struct {
	ChatID int64
	Lang   pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ChatID, arg.Lang)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Name,
		&i.Lang,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}
